name: Base Styles
description: Base styles for the Vermilion theme
type: core

form:
  fields:

    background:
      type: input.colorpicker
      label: Base Background
      default: "#e8ecee"
    background-image:
      type: input.imagepicker
      label: Background Image
      default: "gantry-media://backgrounds/pagesurround/preset1/background.jpg"
    text-color:
      type: input.colorpicker
      label: Base Text Color
      default: "#333333"