name: Base Styles
description: Base styles for the theme
type: core

form:
  fields:
    background:
      type: input.colorpicker
      label: Base Background
      default: "#000000"
    text-color:
      type: input.colorpicker
      label: Base Text Color
      default: "#888888"
    text-active-color:
      type: input.colorpicker
      label: Base Text Active Color
      default: "#f6c167"
    pattern-1:
      type: input.colorpicker
      label: Line Pattern 1
      default: "#f6c167"
    pattern-2:
      type: input.colorpicker
      label: Line Pattern 2
      default: "#ec5a1c"
    pattern-3:
      type: input.colorpicker
      label: Line Pattern 3
      default: "#ffffff"
    pattern-4:
      type: input.colorpicker
      label: Line Pattern 4
      default: "#000000"