version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1563237036
layout:
  /navigation/:
    -
      - 'logo-5679 25'
      - 'menu-2875 75'
  /showcase/:
    -
      - 'position-position-2621 25'
      - 'position-position-4680 25'
      - 'position-position-4839 25'
      - 'position-position-1217 25'
  /top/:
    -
      - 'position-position-7319 25'
      - 'position-position-7699 25'
      - 'position-position-7618 25'
      - 'position-position-4264 25'
  /utility/:
    -
      - 'position-position-3724 25'
      - 'position-position-2653 25'
      - 'position-position-3401 25'
      - 'position-position-1491 25'
  /feature/:
    -
      - 'position-position-4543 25'
      - 'position-position-5434 25'
      - 'position-position-5489 25'
      - 'position-position-8898 25'
  /maintop/:
    -
      - 'position-position-2723 25'
      - 'position-position-7137 25'
      - 'position-position-3102 25'
      - 'position-position-1823 25'
  /expandedtop/:
    -
      - 'position-position-1244 25'
      - 'position-position-1727 25'
      - 'position-position-2593 25'
      - 'position-position-6279 25'
  /container-main/:
    -
      -
        'sidebar 33':
          -
            - position-position-7684
      -
        'main 34':
          -
            - system-content-6489
      -
        'aside 33':
          -
            - position-position-2410
  /expandedbottom/:
    -
      - 'position-position-5886 25'
      - 'position-position-8398 25'
      - 'position-position-7790 25'
      - 'position-position-9029 25'
  /mainbottom/:
    -
      - 'position-position-7827 25'
      - 'position-position-4155 25'
      - 'position-position-2697 25'
      - 'position-position-1720 25'
  /extension/:
    -
      - 'position-position-3769 25'
      - 'position-position-2063 25'
      - 'position-position-6577 25'
      - 'position-position-1027 25'
  /bottom/:
    -
      - 'position-position-2796 25'
      - 'position-position-7267 25'
      - 'position-position-5690 25'
      - 'position-position-7655 25'
  /footer/:
    -
      - 'position-position-4077 25'
      - 'position-position-4480 25'
      - 'position-position-9100 25'
      - 'position-position-6570 25'
  /copyright/:
    -
      - 'position-position-7585 25'
      - 'position-position-1060 25'
      - 'position-position-2009 25'
      - 'position-position-3047 25'
  offcanvas:
    -
      - mobile-menu-4892
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: accent-mobile
      variations: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  top:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  feature:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  maintop:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  expandedtop:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  container-main:
    attributes:
      boxed: ''
  expandedbottom:
    type: section
    attributes:
      boxed: ''
  mainbottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  footer:
    attributes:
      boxed: ''
      class: ''
      variations: ''
  copyright:
    type: section
    attributes:
      boxed: ''
      class: center
      variations: ''
  offcanvas:
    attributes:
      position: g-offcanvas-left
      class: ''
      extra: {  }
      swipe: '0'
      css3animation: '1'
content:
  logo-5679:
    attributes:
      image: 'gantry-media://logo/logo.png'
      link: '1'
      class: g-logo
  menu-2875:
    block:
      class: g-epsilon-menu
      variations: 'center nomarginall nopaddingall'
  position-position-2621:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-position-4680:
    title: 'Showcase B'
    attributes:
      key: showcase-b
  position-position-4839:
    title: 'Showcase C'
    attributes:
      key: showcase-c
  position-position-1217:
    title: 'Showcase D'
    attributes:
      key: showcase-d
  position-position-7319:
    title: 'Top A'
    attributes:
      key: top-a
  position-position-7699:
    title: 'Top B'
    attributes:
      key: top-b
  position-position-7618:
    title: 'Top C'
    attributes:
      key: top-c
  position-position-4264:
    title: 'Top D'
    attributes:
      key: top-d
  position-position-3724:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-position-2653:
    title: 'Utility B'
    attributes:
      key: utility-b
  position-position-3401:
    title: 'Utility C'
    attributes:
      key: utility-c
  position-position-1491:
    title: 'Utility D'
    attributes:
      key: utility-d
  position-position-4543:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-position-5434:
    title: 'Feature B'
    attributes:
      key: feature-b
  position-position-5489:
    title: 'Feature C'
    attributes:
      key: feature-c
  position-position-8898:
    title: 'Feature D'
    attributes:
      key: feature-d
  position-position-2723:
    title: 'Maintop A'
    attributes:
      key: maintop-a
  position-position-7137:
    title: 'MainTop B'
    attributes:
      key: maintop-b
  position-position-3102:
    title: 'MainTop C'
    attributes:
      key: maintop-c
  position-position-1823:
    title: 'MainTop D'
    attributes:
      key: maintop-d
  position-position-1244:
    title: 'Expanded Top A'
    attributes:
      key: expandedtop-a
  position-position-1727:
    title: 'Expanded Top B'
    attributes:
      key: expandedtop-b
  position-position-2593:
    title: 'Expanded Top C'
    attributes:
      key: expandedtop-c
  position-position-6279:
    title: 'Expanded Top D'
    attributes:
      key: expandedtop-d
  position-position-7684:
    title: 'Sidebar A'
    attributes:
      key: sidebar-a
  position-position-2410:
    title: Aside
    attributes:
      key: aside
  position-position-5886:
    title: 'Expanded Bottom A'
    attributes:
      key: expandedbottom-a
  position-position-8398:
    title: 'Expanded Bottom B'
    attributes:
      key: expandedbottom-b
  position-position-7790:
    title: 'Expanded Bottom C'
    attributes:
      key: expandedbottom-c
  position-position-9029:
    title: 'Expanded Bottom D'
    attributes:
      key: expandedbottom-d
  position-position-7827:
    title: 'MainBottom A'
    attributes:
      key: mainbottom-a
  position-position-4155:
    title: 'MainBottom B'
    attributes:
      key: mainbottom-b
  position-position-2697:
    title: 'MainBottom C'
    attributes:
      key: mainbottom-c
  position-position-1720:
    title: 'MainBottom D'
    attributes:
      key: mainbottom-d
  position-position-3769:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-position-2063:
    title: 'Extension B'
    attributes:
      key: extension-b
  position-position-6577:
    title: 'Extension C'
    attributes:
      key: extension-c
  position-position-1027:
    title: 'Extension D'
    attributes:
      key: extension-d
  position-position-2796:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-position-7267:
    title: 'Bottom B'
    attributes:
      key: bottom-b
  position-position-5690:
    title: 'Bottom C'
    attributes:
      key: bottom-c
  position-position-7655:
    title: 'Bottom D'
    attributes:
      key: bottom-d
  position-position-4077:
    title: 'Footer A'
    attributes:
      key: footer-a
  position-position-4480:
    title: 'Footer B'
    attributes:
      key: footer-b
  position-position-9100:
    title: 'Footer C'
    attributes:
      key: footer-c
  position-position-6570:
    title: 'Footer D'
    attributes:
      key: footer-d
  position-position-7585:
    title: 'Copyright A'
    attributes:
      key: copyright-a
  position-position-1060:
    title: 'Copyright B'
    attributes:
      key: copyright-b
  position-position-2009:
    title: 'Copyright C'
    attributes:
      key: copyright-c
  position-position-3047:
    title: 'Copyright D'
    attributes:
      key: copyright-d
  mobile-menu-4892:
    title: 'Mobile Menu'
    block:
      variations: nopaddingtop
