version: 3
preset:
  image: 'genesis-admin://images/layouts/default.png'
  name: default
  timestamp: 1568021052
layout:
  /top/:
    -
      - system-messages-9828
  /navigation/:
    -
      - 'logo-2704 2'
      - 'menu-2872 8'
      - 'button-6662 2'
  /slideshow/:
    -
      - 'position-position-6661 10'
      - 'social-8668 2'
  /header/:
    -
      - position-position-7051
  /above/:
    -
      - position-position-3264
  /feature/:
    -
      - position-position-7980
  /showcase/:
    -
      - position-position-9435
  /utility/:
    -
      - position-position-5239
  /container-main/:
    -
      -
        'sidebar 2':
          -
            - position-position-9414
      -
        'mainbar 7':
          -
            - position-position-8547
          -
            - system-content-1120
      -
        'aside 2':
          -
            - position-position-8807
  /expanded/:
    -
      - position-position-8124
  /extension/:
    -
      - position-position-4800
  /bottom/:
    -
      - position-position-3343
  /container-footer/:
    -
      -
        /footer/:
          -
            - simplemenu-2324
          -
            - newsletter-4035
        /copyright/:
          -
            - copyright-6444
          -
            - particlesjs-5901
  offcanvas:
    -
      - mobile-menu-2576
structure:
  top:
    type: section
    attributes:
      boxed: ''
      class: ''
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  slideshow:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  header:
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  above:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  feature:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings-large
  showcase:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: section-horizontal-paddings
  aside:
    attributes:
      class: ''
  container-main:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings-large'
  extension:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'section-horizontal-paddings section-vertical-paddings'
  bottom:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: section-horizontal-paddings
  footer:
    attributes:
      boxed: ''
      class: 'section-horizontal-paddings section-vertical-paddings medpaddingbottom'
      variations: ''
  copyright:
    type: section
    attributes:
      boxed: ''
      class: section-horizontal-paddings
  container-footer:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  offcanvas:
    attributes:
      swipe: '0'
content:
  logo-2704:
    title: 'Logo / Image'
    attributes:
      image: 'genesis-media://logo/logo.svg'
      link: '1'
      text: pelagia
      title: ''
      class: 'g-logo g-logo-pelagia'
  menu-2872:
    block:
      variations: 'center nopaddingleft nopaddingright'
  button-6662:
    attributes:
      label: 'Get a Quote'
  position-position-6661:
    title: 'Slideshow A'
    attributes:
      key: slideshow-a
    block:
      class: blobs
  social-8668:
    attributes:
      display: icons_only
      items:
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'https://www.facebook.com/Dazzle Software'
          name: Facebook
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/rockettheme'
          name: Twitter
        -
          icon: 'fa fa-github fa-fw'
          text: ''
          link: '#'
          name: GitHub
  position-position-7051:
    title: 'Header A'
    attributes:
      key: header-a
  position-position-3264:
    title: 'Above A'
    attributes:
      key: above-a
  position-position-7980:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-position-9435:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-position-5239:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-position-9414:
    title: 'Sidebar A'
    attributes:
      key: sidebar-a
  position-position-8547:
    title: 'MainBar A'
    attributes:
      key: mainbar-a
  position-position-8807:
    title: 'Aside A'
    attributes:
      key: aside-a
  position-position-8124:
    title: 'Expanded A'
    attributes:
      key: expanded-a
  position-position-4800:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-position-3343:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  simplemenu-2324:
    title: 'Simple Menu'
    attributes:
      menus:
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Product Strategy'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Product Engineering'
            -
              icon: ''
              link: '#'
              target: _blank
              title: Architecture
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'UX / UI Design'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'App Development'
          title: Services
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: Facebook
            -
              icon: ''
              link: '#'
              target: _blank
              title: Instagram
            -
              icon: ''
              link: '#'
              target: _blank
              title: YouTube
            -
              icon: ''
              link: '#'
              target: _blank
              title: Tookapic
            -
              icon: ''
              link: '#'
              target: _blank
              title: Unsplash
          title: Join
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Our Blog'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Case Studies'
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'WebDesign Guides'
            -
              icon: ''
              link: '#'
              target: _blank
              title: Newsletter
            -
              icon: ''
              link: '#'
              target: _blank
              title: 'Favourite Tools'
          title: Resources
        -
          items:
            -
              icon: ''
              link: '#'
              target: _blank
              title: pelagia@rockettheme.com
            -
              icon: ''
              link: '#'
              target: _blank
              title: '1 (800) 123 4567'
          title: Contact
  newsletter-4035:
    attributes:
      layout: g-newsletter-aside
      inputboxtext: 'What''s your email address?'
      buttonclass: ''
  copyright-6444:
    attributes:
      date:
        start: ''
        end: ''
      owner: 'All rights reserved. Designed & Developed by <a href="" target="_blank">Dazzle Software</a>.'
    block:
      variations: center
  particlesjs-5901:
    title: Particles
    attributes:
      sectiononly: enabled
  mobile-menu-2576:
    title: 'Mobile Menu'
