version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1
layout:
  /navigation/:
    -
      - 'logo-1001 25'
      - 'custom-1004 75'
  /container-main/:
    -
      -
        'mainbar 100':
          -
            - system-content-1002
  /footer/:
    -
      - 'copyright-1003 60'
      - 'custom-1005 40'
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  container-main:
    attributes:
      boxed: ''
  footer:
    type: section
    subtype: footer
    attributes:
      boxed: ''
content:
  logo-1001:
    title: 'Logo / Image'
    attributes:
      text: 'Gantry 5 / Helium'
      link: true
  custom-1004:
    title: 'Tagline'
    attributes:
      html: '<div class="g-phpbb-gantry-tagline">phpBB Edition</div>'
  copyright-1003:
    title: Copyright
  custom-1005:
    title: 'Footer note'
    attributes:
      html: '<div class="g-phpbb-gantry-footer-note">Styled by Gantry 5 &amp; Helium</div>'
