name: Base Styles
description: Base styles for the Reiko theme
type: core

form:
  fields:

    background:
      type: input.colorpicker
      label: Base Background
      default: "rgba(255,255,255, 0)"
    background-image:
      type: input.imagepicker
      label: Background Image
      default: "genesis-media://backgrounds/body/img-01.svg"
    text-color:
      type: input.colorpicker
      label: Base Text Color
      default: "#030303"
    text-active-color:
      type: input.colorpicker
      label: Base Text Active Color
      default: "#e0202c"
