services:
    dazzlesoftware.genesis.listener:
        class: dazzlesoftware\genesis\event\listener
        arguments:
            - '@service_container'
            - '@path_helper'
        tags:
            - { name: event.listener }
