atoms:
  -
    type: frameworks
    title: 'JavaScript Frameworks'
    attributes:
      enabled: '1'
      bootstrap:
        enabled: '0'
      mootools:
        enabled: '0'
        more: '0'
    id: frameworks-3899
  -
    id: lightcase-8176
    type: lightcase
    title: Lightcase
    inherit:
      outline: default
      atom: lightcase-8176
      include:
        - attributes
