version: 3
preset:
  image: 'genesis-admin://images/layouts/default.png'
  name: default
  timestamp: 1443731381
layout:
  /top/:
    -
      - system-messages-7514
    -
      - 'position-4355 4'
      - 'position-8729 4'
      - 'position-9861 4'
  /navigation/:
    -
      - 'logo-5870 3'
      - 'menu-8262 9'
    -
      - 'position-8334 4'
      - 'position-1140 4'
      - 'position-8371 4'
  /header/:
    -
      - 'position-5003 4'
      - 'position-1910 4'
      - 'position-1543 4'
  /showcase/:
    -
      - 'position-6037 4'
      - 'position-3664 4'
      - 'position-7866 4'
  /above/:
    -
      - 'position-5415 4'
      - 'position-2538 4'
      - 'position-9586 4'
  /utility/:
    -
      - 'position-1331 4'
      - 'position-1154 4'
      - 'position-1131 4'
  /feature/:
    -
      - 'position-2166 4'
      - 'position-3072 4'
      - 'position-3189 4'
  /container-3787/:
    -
      -
        'sidebar 2':
          -
            - position-5886
      -
        'mainbar 7':
          -
            - 'position-6690 4'
            - 'position-2762 4'
            - 'position-4461 4'
          -
            - system-content-8320
      -
        'aside 2':
          -
            - position-4931
  /expanded/:
    -
      - 'position-5947 4'
      - 'position-9284 4'
      - 'position-6810 4'
  /extension/:
    -
      - 'position-7838 4'
      - 'position-6613 4'
      - 'position-4117 4'
  /bottom/:
    -
      - 'position-6313 4'
      - 'position-9897 4'
      - 'position-5360 4'
  /footer/:
    -
      - 'position-1356 4'
      - 'position-6600 4'
      - 'position-8568 4'
    -
      - 'logo-4284 3'
      - 'horizontalmenu-8782 6'
      - 'social-8066 3'
  /copyright/:
    -
      - 'branding-9739 3'
      - 'copyright-2424 6'
      - 'totop-9744 3'
  /fixedside/:
    -
      - logo-1587
    -
      - social-8525
    -
      - position-8749
  offcanvas:
    -
      - logo-4600
    -
      - social-9203
    -
      - mobile-menu-1304
  0: atoms
structure:
  top:
    type: section
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  above:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
    block:
      columns:
        xs: 2
  mainbar:
    type: section
    block:
      columns:
        xs: 7
  aside:
    block:
      columns:
        xs: 2
  container-3787:
    attributes:
      boxed: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
  extension:
    type: section
    attributes:
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
  fixedside:
    type: section
    title: FixedSide
    attributes:
      boxed: ''
content:
  system-messages-7514:
    layout: false
    block:
      columns:
        xs: 12
      variations: 'nomarginall nopaddingall'
  position-4355:
    title: 'Top A'
    attributes:
      key: top-a
    layout: false
    block:
      columns:
        xs: 4
  position-8729:
    title: 'Top B'
    attributes:
      key: top-b
    layout: false
    block:
      columns:
        xs: 4
  position-9861:
    title: 'Top C'
    attributes:
      key: top-c
    layout: false
    block:
      columns:
        xs: 4
  logo-5870:
    attributes:
      class: 'g-logo g-logo-alt'
      enabled: 0
      image: 'genesis-media://logo/logo-alt.png'
    layout: false
    block:
      class: hidden-phone
      columns:
        xs: 3
  menu-8262:
    attributes:
      enabled: 0
    layout: false
    block:
      columns:
        xs: 9
  position-8334:
    title: 'Navigation A'
    attributes:
      key: navigation-a
    layout: false
    block:
      columns:
        xs: 4
  position-1140:
    title: 'Navigation B'
    attributes:
      key: navigation-b
    layout: false
    block:
      columns:
        xs: 4
  position-8371:
    title: 'Navigation C'
    attributes:
      key: navigation-c
    layout: false
    block:
      columns:
        xs: 4
  position-5003:
    title: 'Header A'
    attributes:
      key: header-a
    layout: false
    block:
      columns:
        xs: 4
  position-1910:
    title: 'Header B'
    attributes:
      key: header-b
    layout: false
    block:
      columns:
        xs: 4
  position-1543:
    title: 'Header C'
    attributes:
      key: header-c
    layout: false
    block:
      columns:
        xs: 4
  position-6037:
    title: 'Showcase A'
    attributes:
      key: showcase-a
    layout: false
    block:
      columns:
        xs: 4
  position-3664:
    title: 'Showcase B'
    attributes:
      key: showcase-b
    layout: false
    block:
      columns:
        xs: 4
  position-7866:
    title: 'Showcase C'
    attributes:
      key: showcase-c
    layout: false
    block:
      columns:
        xs: 4
  position-5415:
    title: 'Above A'
    attributes:
      key: above-a
    layout: false
    block:
      columns:
        xs: 4
  position-2538:
    title: 'Above B'
    attributes:
      key: above-b
    layout: false
    block:
      columns:
        xs: 4
  position-9586:
    title: 'Above C'
    attributes:
      key: above-c
    layout: false
    block:
      columns:
        xs: 4
  position-1331:
    title: 'Utility A'
    attributes:
      key: utility-a
    layout: false
    block:
      columns:
        xs: 4
  position-1154:
    title: 'Utility B'
    attributes:
      key: utility-b
    layout: false
    block:
      columns:
        xs: 4
  position-1131:
    title: 'Utility C'
    attributes:
      key: utility-c
    layout: false
    block:
      columns:
        xs: 4
  position-2166:
    title: 'Feature A'
    attributes:
      key: feature-a
    layout: false
    block:
      columns:
        xs: 4
  position-3072:
    title: 'Feature B'
    attributes:
      key: feature-b
    layout: false
    block:
      columns:
        xs: 4
  position-3189:
    title: 'Feature C'
    attributes:
      key: feature-c
    layout: false
    block:
      columns:
        xs: 4
  position-5886:
    title: Sidebar
    attributes:
      key: sidebar
    layout: false
    block:
      columns:
        xs: 12
  position-6690:
    title: 'Mainbar A'
    attributes:
      key: mainbar-a
    layout: false
    block:
      columns:
        xs: 4
  position-2762:
    title: 'Mainbar B'
    attributes:
      key: mainbar-b
    layout: false
    block:
      columns:
        xs: 4
  position-4461:
    title: 'Mainbar C'
    attributes:
      key: mainbar-c
    layout: false
    block:
      columns:
        xs: 4
  system-content-8320:
    layout: false
    block:
      columns:
        xs: 12
  position-4931:
    title: Aside
    attributes:
      key: aside
    layout: false
    block:
      columns:
        xs: 12
  position-5947:
    title: 'Expanded A'
    attributes:
      key: expanded-a
    layout: false
    block:
      columns:
        xs: 4
  position-9284:
    title: 'Expanded B'
    attributes:
      key: expanded-b
    layout: false
    block:
      columns:
        xs: 4
  position-6810:
    title: 'Expanded C'
    attributes:
      key: expanded-c
    layout: false
    block:
      columns:
        xs: 4
  position-7838:
    title: 'Extension A'
    attributes:
      key: extension-a
    layout: false
    block:
      columns:
        xs: 4
  position-6613:
    title: 'Extension B'
    attributes:
      key: extension-b
    layout: false
    block:
      columns:
        xs: 4
  position-4117:
    title: 'Extension C'
    attributes:
      key: extension-c
    layout: false
    block:
      columns:
        xs: 4
  position-6313:
    title: 'Bottom A'
    attributes:
      key: bottom-a
    layout: false
    block:
      columns:
        xs: 4
  position-9897:
    title: 'Bottom B'
    attributes:
      key: bottom-b
    layout: false
    block:
      columns:
        xs: 4
  position-5360:
    title: 'Bottom C'
    attributes:
      key: bottom-c
    layout: false
    block:
      columns:
        xs: 4
  position-1356:
    title: 'Footer A'
    attributes:
      key: footer-a
    layout: false
    block:
      columns:
        xs: 4
      class: g-title-bordered
  position-6600:
    title: 'Footer B'
    attributes:
      key: footer-b
    layout: false
    block:
      columns:
        xs: 4
      class: g-title-bordered
  position-8568:
    title: 'Footer C'
    attributes:
      key: footer-c
    layout: false
    block:
      columns:
        xs: 4
      class: g-title-bordered
  logo-4284:
    attributes:
      class: 'g-logo g-logo-alt'
      image: 'genesis-media://logo/logo-alt.png'
    layout: false
    block:
      columns:
        xs: 3
  horizontalmenu-8782:
    title: 'Horizontal Menu'
    attributes:
      items:
        -
          text: Genesis
          link: 'https://dazzlecms.org/'
          name: Genesis
        -
          text: Features
          link: 'https://codex.dazzlecms.org/basics/key-features'
          name: Features
        -
          text: Particles
          link: 'https://codex.dazzlecms.org/particles'
          name: Particles
        -
          text: Join
          link: 'https://dazzlesoftware.org/join'
          name: Join
    layout: false
    block:
      columns:
        xs: 6
      class: g-horizontalmenu-block
      variations: center
  social-8066:
    layout: false
    block:
      columns:
        xs: 3
  branding-9739:
    attributes:
      content: 'Powered by <a href="https://dazzlecms.org/" title="Genesis Framework" class="g-powered-by">Genesis<span class="hidden-tablet"> Framework</span></a>'
    layout: false
    block:
      columns:
        xs: 3
  copyright-2424:
    layout: false
    block:
      columns:
        xs: 6
  totop-9744:
    title: 'To Top'
    attributes:
      icon: 'fa fa-arrow-circle-o-up fa-2x'
      content: ''
    layout: false
    block:
      columns:
        xs: 3
  logo-1587:
    attributes:
      class: 'g-fixedside-logo g-logo-alt'
    layout: false
    block:
      columns:
        xs: 12
  social-8525:
    layout: false
    block:
      columns:
        xs: 12
  position-8749:
    title: 'Module Position'
    attributes:
      key: fixedside
    layout: false
    block:
      columns:
        xs: 12
  logo-4600:
    attributes:
      class: 'g-offcanvas-logo g-logo-alt'
    layout: false
    block:
      columns:
        xs: 12
      class: 'nomarginall nopaddingall'
  social-9203:
    layout: false
    block:
      columns:
        xs: 12
      class: 'nomarginall nopaddingall center'
  mobile-menu-1304:
    title: 'Mobile Menu'
    layout: false
    block:
      columns:
        xs: 12
  atoms:
    attributes:
      name: 'Atoms Section'
      boxed: ''
    layout: false
