<?php

declare(strict_types=1);

/**
 * @package   Genesis
 * @author    Dazzle Software https://dazzlesoftware.org
 * @copyright Copyright (C) 2026 Dazzle Software, LLC
 * @license   GNU/GPLv3 and later
 */

namespace Genesis\Framework;

use Joomla\CMS\Language\Text;
use Genesis\Admin\ThemeList;
use Genesis\Component\Filesystem\Folder;
use Genesis\Component\Outline\OutlineCollection;
use Genesis\Debugger;
use Genesis\Joomla\StyleHelper;
use Joomla\CMS\Application\CMSApplication;
use Joomla\CMS\Factory;
use DazzleSoftware\Toolbox\ResourceLocator\UniformResourceLocator;

/**
 * Class Outlines
 * @package Genesis\Framework
 */
class Outlines extends OutlineCollection
{
    /** @var int */
    protected ?string $createId = null;

    /**
     * @param int|string $id
     * @return int|string
     */
    public function preset(string|int $id): string|int
    {
        if (is_numeric($id)) {
            $style = StyleHelper::getStyle((int) $id);
            $params = json_decode($style->params, true);

            $id = isset($params['preset']) ? $params['preset'] : 'default';
        }

        return $id;
    }

    /**
     * @param object|null $template
     * @return mixed
     */
    public function current(?object $template = null): string|int|null
    {
        /** @var CMSApplication $application */
        $application = Factory::getApplication();

        if (!is_object($template)) {
            // Get the template style.
            $template = $application->getTemplate(true);
        }

        $preset = $template->params->get('preset', 'default');
        $outline = $template->params->get('configuration', !empty($template->id) ? $template->id : null);

        if (\GENESIS_DEBUGGER) {
            Debugger::addMessage('Template Style:' . $template);
        }

        if (JDEBUG && !$outline) {
            static $shown = false;

            if (!$shown) {
                $shown = true;
                $application->enqueueMessage('[DEBUG] JApplicationSite::getTemplate() was overridden with no specified Genesis outline.', 'notice');
            }
        }

        /** @var UniformResourceLocator $locator */
        $locator = $this->container['locator'];

        return ($outline && is_dir($locator("{$this->path}/{$outline}"))) ? $outline : $preset;
    }

    /**
     * @param string $path
     * @return $this
     */
    public function load(string $path = 'genesis-config://'): static
    {
        $this->path = $path;

        $genesis = $this->container;

        $theme = isset($genesis['theme.name']) ? $genesis['theme.name'] : null;

        $styles = ThemeList::getStyles($theme);

        $installer = new ThemeInstaller($this->container['theme.name']);
        $title = $installer->getStyleName('%s - ');

        $outlines = [];
        foreach ($styles as $style) {
            $preset = isset($style->params['preset']) ? $style->params['preset'] : null;
            $outline = isset($style->params['configuration']) ? $style->params['configuration'] : $preset;

            if ($outline && $outline != $style->id) {
                // New style generated by Joomla.
                StyleHelper::copy($style, $outline, $style->id);
            }
            $outlines[$style->id] = preg_replace('|^' . preg_quote($title, '|') . '|', '', $style->style);
        }

        asort($outlines);

        $this->items = $this->addDefaults($outlines);

        return $this;
    }

    /**
     * @param string|null $id
     * @param string $title
     * @param string|array $preset
     * @return string
     * @throws \RuntimeException
     */
    public function create(?string $id, ?string $title = null, string|array|null $preset = null): string
    {
        if ($this->createId) {
            // Workaround Joomla wanting to use different logic for style duplication.
            $new = parent::create($this->createId, $title, $preset);

            $this->createId = null;

            return $new;
        }

        $title = $title ? "%s - {$title}" : '%s - Untitled';

        $installer = new ThemeInstaller($this->container['theme.name']);
        $title = $installer->getStyleName($title);
        $style = $installer->addStyle($title);

        $presetId = (string) (isset($preset['preset']['name']) ? $preset['preset']['name'] : ($preset ?: 'default'));

        StyleHelper::update($style->id, $presetId);

        // Create configuration folder.
        $newId = parent::create((string) $style->id, $title, $preset);

        if ($newId != $style->id) {
            throw new \RuntimeException(sprintf("Creating outline: folder '%s' already exists!", $style->id));
        }

        return (string) $style->id;
    }

    /**
     * @param string $id
     * @param null $title
     * @param bool $inherit
     * @return string
     * @throws \RuntimeException
     */
    public function duplicate(string $id, ?string $title = null, bool $inherit = false): string
    {
        if (!$this->canDuplicate($id)) {
            throw new \RuntimeException("Outline '$id' cannot be duplicated", 400);
        }

        // Handle special case of duplicating system outlines.
        if ((string)(int) $id !== (string) $id) {
            return parent::duplicate($id, $title, $inherit);
        }

        // Use Joomla logic to duplicate the style.
        $model = StyleHelper::loadModel();
        $pks = [$id];

        try {
            $model->duplicate($pks);
        } catch (\Exception $e) {
            throw new \RuntimeException($e->getMessage(), 400, $e);
        }

        // Seek the newly generated style ID since Joomla doesn't return one on duplication.
        $theme = $this->container['theme.name'];
        $styles = ThemeList::getStyles($theme, true);
        $style = end($styles);

        if ($title) {
            // Change the title.
            $installer = new ThemeInstaller($theme);
            $title = $installer->getStyleName("%s - {$title}");
            $this->rename($style->id, $title);
        } else {
            $title = $style->style;
        }

        $this->createId = (string) $style->id;

        return parent::duplicate($id, $title, $inherit);
    }

    /**
     * @param string $id
     * @param string $title
     * @return string
     * @throws \RuntimeException
     */
    public function rename(string $id, string $title): string
    {
        $model = StyleHelper::loadModel();

        $item = $model->getTable();
        $item->load($id);

        if (!$item->id) {
            throw new \RuntimeException('Outline not found', 404);
        }

        $theme = $this->container['theme.name'];
        $installer = new ThemeInstaller($theme);

        $title = $title ? "%s - {$title}" : '%s - Untitled';
        $title = $installer->getStyleName($title);

        $item->title = $title;

        if (!$item->check()) {
            throw new \RuntimeException(Text::_('GENESIS_ERROR_OUTLINE_VALIDATION_FAILED'), 400);
        }

        if (!$item->store()) {
            throw new \RuntimeException(Text::_('GENESIS_ERROR_OUTLINE_STORE_FAILED'), 500);
        }

        if (isset($this->items[$id])) {
            $this->items[$id] = $title;
        }

        return $id;
    }

    /**
     * @param string $id
     * @param bool $deleteModel
     * @throws \Exception
     */
    public function delete(string $id, bool $deleteModel = true): void
    {
        if (!$this->canDelete($id)) {
            throw new \RuntimeException("Outline '$id' cannot be deleted", 400);
        }

        $model = StyleHelper::loadModel();

        $item = $model->getTable();
        $item->load($id);

        try {
            foreach ($this->getInheritingOutlines($id) as $outline => $title) {
                $this->layout($outline)->updateInheritance($id)->save()->saveIndex();
            }
            foreach ($this->getInheritingOutlinesWithAtom($id) as $outline => $title) {
                Atoms::instance($outline)->updateInheritance($id)->save();
            }

            if ($deleteModel && !$model->delete($id)) {
                $messages = Factory::getApplication()->getMessageQueue();
                $message = reset($messages);
                $error = $message ? $message['message'] : 'Unknown error';
                throw new \RuntimeException($error);
            }
        } catch (\Exception $e) {
            throw new \RuntimeException('Deleting outline failed: ' . $e->getMessage(), 400, $e);
        }

        // Remove configuration directory.
        $genesis = $this->container;

        /** @var UniformResourceLocator $locator */
        $locator = $genesis['locator'];
        $path = $locator->findResource("{$this->path}/{$item->id}", true, true);
        if ($path) {
            if (file_exists($path)) {
                Folder::delete($path);
            }
        }

        unset($this->items[$item->id]);
    }

    /**
     * @param string $id
     * @return boolean
     */
    public function canDelete(string $id): bool
    {
        $style = StyleHelper::getStyle($id);

        return !(!$style->id || $style->home);
    }

    /**
     * @param string $id
     * @return boolean
     */
    public function isDefault(string $id): bool
    {
        $style = StyleHelper::getStyle($id);

        return (bool) $style->home;
    }
}
