version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: services
  timestamp: 1443176112
layout:
  navigation: {  }
  /showcase/:
    -
      - custom-8468
  top: {  }
  utility: {  }
  feature: {  }
  /maintop/:
    -
      - 'custom-7934 33.3'
      - 'custom-9095 33.3'
      - 'custom-1474 33.3'
    -
      - 'custom-6648 33.3'
      - 'custom-4304 33.3'
      - 'custom-1810 33.3'
  expandedtop: {  }
  /main/:
    -
      -
        'mainbody 67':
          -
            - custom-9767
      -
        'sidebar 33':
          -
            - custom-6672
          -
            - custom-1548
          -
            - custom-4119
  expandedbottom: {  }
  /mainbottom/:
    -
      - custom-3376
  extension: {  }
  /footer-surround/:
    -
      -
        /bottom/:
          -
            - custom-4488
        /footer/:
          -
            - 'custom-5551 50'
            - 'custom-2913 50'
  copyright: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  showcase:
    type: section
    attributes:
      boxed: ''
      class: rt-overlay-dark
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  feature:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  maintop:
    type: section
    attributes:
      boxed: ''
      class: 'xlargepaddingbottom rt-overlay-light'
  expandedtop:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  mainbody:
    type: section
    attributes:
      class: ''
  sidebar:
    type: section
    attributes:
      class: ''
    block:
      class: largemargintop
  main:
    type: container
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  expandedbottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  mainbottom:
    type: section
    attributes:
      boxed: ''
      class: rt-overlay-light
  extension:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  bottom:
    type: section
    attributes:
      boxed: ''
      class: rt-overlay-dark
  footer:
    attributes:
      boxed: ''
      class: rt-overlay-dark
  footer-surround:
    type: container
    title: 'Footer Surround'
    attributes:
      boxed: '3'
      class: ''
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - block
        - children
content:
  custom-8468:
    title: Services
    attributes:
      title: 'Services<span class="rt-title-tag">What We Can Do For You</span>'
      html: ''
    block:
      class: rt-big-title
      variations: center
  custom-7934:
    title: 'Web Development'
    attributes:
      title: ''
      html: "<span class=\"rt-icon\"><span class=\"fa fa-cogs\"></span></span>\n<h1 class=\"title rt-capitalize\">Web Development</h1>\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n<a class=\"readon\" href=\"#\">Read More</a>"
    block:
      class: nomarginbottom
      variations: center
  custom-9095:
    title: 'Graphic Design'
    attributes:
      title: ''
      html: "<span class=\"rt-icon\"><span class=\"fa fa-bar-chart\"></span></span>\n<h1 class=\"title rt-capitalize\">Graphic Design</h1>\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n<a class=\"readon\" href=\"#\">Read More</a>"
    block:
      class: nomarginbottom
      variations: center
  custom-1474:
    title: 'Web Hosting'
    attributes:
      title: ''
      html: "<span class=\"rt-icon\"><span class=\"fa fa-cloud\"></span></span>\n<h1 class=\"title rt-capitalize\">Web Hosting</h1>\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n<a class=\"readon\" href=\"#\">Read More</a>"
    block:
      class: nomarginbottom
      variations: center
  custom-6648:
    title: 'Movie Maker'
    attributes:
      title: ''
      html: "<span class=\"rt-icon\"><span class=\"fa fa-film\"></span></span>\n<h1 class=\"title rt-capitalize\">Movie Maker</h1>\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n<a class=\"readon\" href=\"#\">Read More</a>"
    block:
      class: nomarginbottom
      variations: center
  custom-4304:
    title: 'Music Studio'
    attributes:
      title: ''
      html: "<span class=\"rt-icon\"><span class=\"fa fa-music\"></span></span>\n<h1 class=\"title rt-capitalize\">Music Studio</h1>\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n<a class=\"readon\" href=\"#\">Read More</a>"
    block:
      class: nomarginbottom
      variations: center
  custom-1810:
    title: 'Web Translator'
    attributes:
      title: ''
      html: "<span class=\"rt-icon\"><span class=\"fa fa-comments\"></span></span>\n<h1 class=\"title rt-capitalize\">Web Translator</h1>\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n<a class=\"readon\" href=\"#\">Read More</a>"
    block:
      class: nomarginbottom
      variations: center
  custom-9767:
    title: 'Custom HTML'
    attributes:
      title: ''
      html: "<div class=\"gantry-width-block gantry-width-50\">\n\t<div class=\"gantry-width-spacer\">\n\t\t<span class=\"rt-image\">\n\t\t\t<img src=\"gantry-media://pages/services/img1.jpg\" alt=\"image\" />\n\t\t</span>\n\t</div>\n</div>\n\n<div class=\"gantry-width-block gantry-width-50\">\n\t<div class=\"gantry-width-spacer\">\n\t\t<h3>Freelance Services</h3>\n\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet, odio, enim quam temporibus ratione dolor iusto animi similique possimus at? <span class=\"hidden-tablet hidden-phone\">Veritatis, a atque odio nam quisquam perferendis magnam necessitatibus laboriosam!</span></p>\n\t\t<ul>\n\t\t\t<li>Lorem ipsum dolor sit amet.</li>\n\t\t\t<li>Aliquam tincidunt mauris eu risus.</li>\n\t\t\t<li>Sitque odio nam quisquam risus.</li>\n\t\t</ul>\t\n\t\t<a href=\"#\" class=\"readon\">Learn More</a>\t\n\t</div>\n</div>\n\n<div class=\"clear\"></div><hr />\n\n<div class=\"gantry-width-block gantry-width-50\">\n\t<div class=\"gantry-width-spacer\">\n\t\t<h3>Team Collaboration</h3>\n\t\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet, odio, enim quam temporibus ratione dolor iusto animi similique possimus at? <span class=\"hidden-tablet hidden-phone\">Veritatis, a atque odio nam quisquam perferendis magnam necessitatibus laboriosam!</span></p>\t\n\t\t<ul>\n\t\t\t<li>Lorem ipsum dolor sit amet.</li>\n\t\t\t<li>Aliquam tincidunt mauris eu risus.</li>\n\t\t\t<li>Sitque odio nam quisquam risus.</li>\n\t\t</ul>\t\n\t\t<a href=\"#\" class=\"readon\">Learn More</a>\t\t\n\t</div>\t\t\n</div>\n\n<div class=\"gantry-width-block gantry-width-50\">\n\t<div class=\"gantry-width-spacer\">\n\t\t<span class=\"rt-image\">\n\t\t\t<img src=\"gantry-media://pages/services/img1.jpg\" alt=\"image\" />\n\t\t</span>\n\t</div>\n</div>\n\n<div class=\"clear\"></div>"
  custom-6672:
    title: 'Cloud Services'
    attributes:
      title: '<i class="fa fa-cloud-download title-icon"></i>Cloud Services'
      html: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptate pariatur officia accusantium sapiente expedita eius fugiat</p>\n<a href=\"#\" class=\"readon\">Learn More</a>"
    block:
      class: medmarginbottom
      variations: box3
  custom-1548:
    title: 'Secured Data'
    attributes:
      title: '<i class="fa fa-shield title-icon"></i>Secured Data'
      html: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptate pariatur officia accusantium sapiente expedita eius fugiat</p>\n<a href=\"#\" class=\"readon\">Learn More</a>"
    block:
      class: medmarginbottom
      variations: box3
  custom-4119:
    title: '24/7 Support'
    attributes:
      title: '<i class="fa fa-road title-icon"></i>24/7 Support'
      html: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptate pariatur officia accusantium sapiente expedita eius fugiat</p>\n<a href=\"#\" class=\"readon\">Learn More</a>"
    block:
      variations: box3
  custom-3376:
    title: 'Want to Work With Us?'
    attributes:
      title: 'Want to Work With Us?'
      html: "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, voluptate pariatur officia accusantium sapiente expedita eius fugiat ea distinctio et rem sed quo amet atque dignissimos autem quos asperiores dolorum!</p>\n\n<div class=\"rt-readon-row\">\n\t<a href=\"#\" class=\"readon rt-large-button\"><span class=\"fa fa-file-text\"></span> Contact Us</a>\n</div>\t"
    block:
      class: rt-big-title
      variations: center
  custom-4488:
    title: 'More Details'
    attributes:
      title: 'More Details <span class="rt-title-tag">Help guides are available to assist</span>'
      html: ''
    block:
      class: rt-big-title
      variations: center
  custom-5551:
    title: 'Pages Demo Footer'
    attributes:
      title: ''
      html: "<p>All demo content is for sample purpose only, intended to show a live site. Use the <a href=\"#\">Anacron RocketLauncher</a> to install an equivalent of the demo onto your site.</p>\n<p>Anacron is only available as part of the Club Subscription.</p>\n\n<div class=\"gantry-width-block gantry-width-50\">\n\t<div class=\"gantry-width-spacer\">\n\t\t<div class=\"rt-footer-logo\"></div>\n\t</div>\n</div>\n\n<div class=\"gantry-width-block gantry-width-50\">\n\t<div class=\"gantry-width-spacer nomarginleft\">\n\t\t<span>+1-(678)-123-6789</span><br />\n\t\t<span>Anacron Center, LLC</span><br />\n\t\t<span>123 Boulevard</span><br />\n\t\t<span>Seattle, WA 00000, USA</span><br />\n\t\t<span><a href=\"#\">hello@anacron.com</a></span>\n\t</div>\n</div>\n\n<div class=\"clear\"></div>"
  custom-2913:
    title: 'Pages Footer Form'
    attributes:
      title: ''
      html: "<div class=\"rt-email-form\">\n\t<form action=\"#\">\n\t\t<input type=\"text\" placeholder=\"Full Name\" size=\"18\" alt=\"fullname\" class=\"inputbox\" name=\"fullname\">\n\t\t<input type=\"text\" placeholder=\"Your Email\" size=\"28\" alt=\"email\" class=\"inputbox\" name=\"email\">\n\t\t<textarea placeholder=\"Your Message\" name=\"message\" cols=\"30\" rows=\"5\"></textarea>\n\t\t<input type=\"submit\" value=\"Send Message\" class=\"button\" name=\"send\">\n\t</form>\t\n</div>"
